### ISSUE TITLE
'Addresses' should be Value-Object

### ISSUE THREAD

**Issue by Nongzhsh** [Hitasp/Tradegram#2]
'Addresses' should be Value-Object, but a customer have multiple addresses (or an user address book have many addresses), how do store Value-Object collection to db?  toJson()?

**Comment by hitaspdotnet** [comment]
we can skip skip value-object design pattern for now. and customer address book too. Each customer must have 2 addresses (billing, shipping). we can reference address by ID in customer entity and extend CustomerLookupService for customer addresses or create new addressLookupService.
I have opened new issue for this. #3  
GL.
